import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

/*
 * Flat config, using eslint-config-next's native flat exports.
 *
 * `FlatCompat` is deliberately NOT used. Wrapping the Next.js preset in
 * `@eslint/eslintrc`'s compatibility layer throws "Converting circular structure
 * to JSON" under ESLint 9, because the preset carries plugin objects that the
 * legacy normaliser cannot serialise. The v16 presets are already flat arrays,
 * so extending them directly is both simpler and correct.
 */
const eslintConfig = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      // Generated by `npm run generate:types`. Never hand-edited.
      'src/payload-types.ts',
      // Written by Payload. Never hand-edited.
      'src/app/(payload)/admin/importMap.js',
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
]

export default eslintConfig
